package constants

// 日志模板集中管理。
const (
	LogUserLoginSuccess       = "user login success"
	LogUserLoginFailed        = "user login failed"
	LogUserRegisterSuccess    = "user register success"
	LogUserProfileUpdate      = "user profile update"
	LogWarehouseCreateSuccess = "warehouse create success"
	LogWarehouseUpdateSuccess = "warehouse update success"
	LogWarehouseStatusChange  = "warehouse status change"
	LogShelfCreateSuccess     = "shelf create success"
	LogShelfUpdateSuccess     = "shelf update success"
	LogCategoryCreateSuccess  = "category create success"
	LogProductCreateSuccess   = "product create success"
	LogProductUpdateSuccess   = "product update success"
	LogOrderCreateSuccess     = "stock order create success"
	LogOrderCreateFailed      = "stock order create failed"
	LogOrderSubmitSuccess     = "stock order submit success"
	LogOrderSubmitFailed      = "stock order submit failed"
	LogOrderApproveSuccess    = "stock order approve success"
	LogOrderExecuteSuccess    = "stock order execute success"
	LogOrderExecuteFailed     = "stock order execute failed"
	LogOrderCancelSuccess     = "stock order cancel success"
	LogStockInboundSuccess    = "stock inbound success"
	LogStockOutboundSuccess   = "stock outbound success"
	LogStockOutboundFailed    = "stock outbound failed"
	LogStockTransferSuccess   = "stock transfer success"
	LogStockAdjustSuccess     = "stock adjust success"
	LogStockQuery             = "stock query"
	LogInventoryReport        = "inventory check report"
	LogDashboardStats         = "dashboard stats"
	LogOperationWriteFailed   = "operation log write failed"
	LogRateLimitHit           = "rate limit hit"
)
